inputs:
  registry-url:
    required: false
runs:
  using: composite
  steps:
    -
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: ${{ inputs.registry-url }}
