name: Publish

on:
 release:
   types: [created] # will be triggered when a NON-draft release is created and published.

jobs:
  publish-npm:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master # otherwise it defaults to the version tag missing bump commit
          fetch-depth: 0 # fetch all history
      - name: Checkout to bump commit
        run: git checkout "$(git rev-list "${{ github.event.release.tag_name }}"..master | tail -1)"
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master # otherwise it defaults to the version tag missing bump commit
          fetch-depth: 0 # fetch all history
      - name: Checkout to bump commit
        run: git checkout "$(git rev-list "${{ github.event.release.tag_name }}"..master | tail -1)"
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          registry-url: https://registry.npmjs.org/
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: undergroundwires
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: undergroundwires/bump-everywhere
          tag_with_ref: true
          tags: latest